version: '2'

services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017

  server:
    container_name: server
    build: './server'
    restart: always
    ports:
      - 4000:3000
    depends_on: 
      - mongo
    environment: 
      MONGO_URL: mongodb://mongo:27017/db

  app:
    container_name: app
    build: './client'
    ports:
      - 2019:2019
      - 3000:80
